defaults:
  - _self_
  - model: r18.yaml
  - dataset: frames_steering.yaml

val_pct: 0.02

# train
lr: 1e-3
batch_size: 8
gradient_accumulation_steps: 1
epochs: 1
val_freq: 20 # number of time we eval per epoch

# debug
# null = don't overfit
overfit_batches: null

# data loading
num_workers: 8
pin_memory: True

# model
model_artifact_name: null

# reproducibility
seed: 1234
cudnn_deterministic: False

# logging
wandb:
  project: "skyline_trajectory_prediction"
  job_type: "train"
